server: irc.libera.chat:+6697
nickname: bismite
password: bismite:hunter2
channel: "#libera-masks"
database: ~/.masks.db

sasl:
  username: bismite
  password: hunter3

oper:
  name: bismite
  pass: hunter4
  # oper via CHALLENGE key instead
  #file: ~/libera.key

reasons:
  tos:  "You have violated Libera Chat's terms of service. Email bans@libera.chat with questions."
  spam: "Spam is not welcome on Libera Chat. Email bans@libera.chat with questions."
