server: irc.libera.chat:+6697
nickname: bismite
password: bismite:hunter2
channel: "#libera-masks"
database: ~/.masks.db

sasl:
  username: bismite
  password: hunter3

oper:
  name: bismite
  pass: hunter4
  # oper via CHALLENGE key instead
  #file: ~/libera.key

bancmd: "KLINE 1440 {ident}@{user.ip} :{reason}"
cliconnre: '^:[^!]+ NOTICE \* :\*{3} Notice -- Client connecting: (?P<nick>\S+) .(?P<user>[^!]+)@(?P<host>\S+). .(?P<ip>[^]]+). \S+ .(?P<real>.+).$'
cliexitre: '^:[^!]+ NOTICE \* :\*{3} Notice -- Client exiting: (?P<nick>\S+) '
clinickre: '^:[^!]+ NOTICE \* :\*{3} Notice -- Nick change: From (?P<old>\S+) to (?P<new>\S+) .*$'
