server: irc.libera.chat:+6697
nickname: jmasks
password: jmasks:hunter2
channel: "#libera-masks"
database: ~/.masks.db

sasl:
  username: jmasks
  password: hunter3

oper:
  name: jmasks
  file: ~/libera.key
  pass: hunter4

reasons:
  tos:  "You have violated Libera Chat's terms of service. Email bans@libera.chat with questions."
  spam: "Spam is not welcome on Libera Chat. Email bans@libera.chat with questions."
